@startuml
abstract class KeyFluxBase {
    Key : object <<get>>
    + <<virtual>> Store(callback:Action, condition:bool) : void
    + <<virtual>> Dispatch() : void
    + <<virtual>> Store(callback:Action<T2>, condition:bool) : void
    + <<virtual>> Dispatch(@param:T2) : void
    + <<virtual>> Store(callback:Func<T2>, condition:bool) : void
    + <<virtual>> Dispatch() : T2
    + <<virtual>> Store(callback:Func<T2, T3>, condition:bool) : void
    + <<virtual>> Dispatch(@param:T2) : T3
    + <<virtual>> StoreState(callback:Action<T2>, condition:bool) : void
    + <<virtual>> DispatchState(@param:T2) : void
}
ScriptableObject <|-- KeyFluxBase
IKeyFlux <|-- KeyFluxBase
@enduml
