@startuml
class RollbackObject <<sealed>> {
    Save(_state:object) : void
    Reverse(fpsToReverse:int) : void
    Undo() : void
}
class "Action`1"<T> {
}
IRollback <|-- RollbackObject
RollbackObject --> "OnSave<(int fps, object state)>" "Action`1"
RollbackObject --> "OnReverse<(int fps, object state)>" "Action`1"
RollbackObject --> "OnReverseError<(int fps, int fpsToReverse)>" "Action`1"
RollbackObject --> "OnUndoError" Action
RollbackObject --> "OnUndo<(int fps, object state)>" "Action`1"
@enduml
