@startuml
class OWOModule <<sealed>> {
    AutoConnect() : Task
    Connect(ip:string) : Task
    Disconnect() : Task
    Send(frequency:int, durationSeconds:float, intensityPercentage:int, rampUpMillis:float, rampDownMillis:float, exitDelaySeconds:float, muscles:(int id, int intensity)[]) : Task
    Stop() : Task
}
MonoFlux <|-- OWOModule
IOWO <|-- OWOModule
OWOModule --> "State" ConnectionState
@enduml
