@startuml
class OWOService <<static>> <<partial>> {
}
class OWOService <<static>> <<partial>> {
}
class OWOService <<static>> <<partial>> {
}
class Data <<static>> <<partial>> {
}
class Key <<static>> <<partial>> {
    + <<const>> Module : string
    + <<const>> OnConnectionState : string
    + <<const>> AutoConnect : string
    + <<const>> Connect : string
    + <<const>> Disconnect : string
    + <<const>> Send : string
    + <<const>> Stop : string
}
OWOService --> "Module" IOWO
OWOService +-- Data
OWOService +-- Key
@enduml
